language: swift
osx_image: xcode9.3
script: make ci
xcode_project: BubbleUp
xcode_scheme: BubbleUp
env:
  global:
  - FRAMEWORK_NAME=BubbleUp
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - make lint
before_deploy:
  - carthage build --no-skip-current
  - carthage archive $FRAMEWORK_NAME
