language: swift
osx_image: xcode10.2
script: make ci
branches:
  only:
    - master
    - /^\d+\.\d+\.\d+$/
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - make lint
  - carthage bootstrap
before_deploy:
  - carthage build --no-skip-current
  - carthage archive BubbleUp
notifications:
  irc: "chat.freenode.net#repla-development"
deploy:
  provider: releases
  api_key:
    secure: BbW/b2MUPoX17BbfG3GfSDQdsMG1PUqGje+vDu/ztNgdmzBJu9RQNHejrr51M41fnFrh0FY5VldR7MxIN8ZS5MBFk3rt7yHmgP8hg+YZTSDVHxVq7juu3SqWI2xnLJclB2mxMFiN8UVi0/+UGw2Sq4ZlF90T8Tc7+tUHNf4Xj+E/Q9jjkECI/WL++WNRRfEUFLkY7/xUSJXZjCsexsDWqzFOiJ9qOok6Ot5rikkm6hE687FaX2MABcIOD2hHNdXg8qsuvkJ1E3ZJ1ZuqgekmN09kObvVM3KDmLLcYh+Hk+1sOoTUJbvOv/A8XNVL8Vzsvs5UHm80G4IWDgd2qS/GxcuMqI5gsLVY4aUstVndq/3gZ28oS4ZI5Bdv9OKDR0gQJqKMjdsmREULQzFmAU5gPINmnRUSvofZHObfEXj2ua3XnuYBVsSINMPVpXDvNqL3K3woo4Lcpkv7Op30b+BcNvEvJgELo0OyDrHQomvUPPk1doml2lmkUlUf1o93HVl4Ne8ip1Ywy+IU1pVYmNt9rGQXGoZjz9GMRuBnS8A62Pd9rg4rVBVMqhRUF1B+wwMJPbaqjtN8m6YWN0t+UbnzV4VBC0aH0qG+qXwl6OOfchkeubgX3YK10c9ZE+eiF85LtTxOt/W3nFKtnRAihEyQxB/yKPhFWM0TGOSnLfuCpC8=
  file: BubbleUp.framework.zip
  skip_cleanup: true
  on:
    repo: robenkleene/BubbleUp
    tags: true
env:
  global:
    secure: RF+6VFM7EJwSiXH0X20aXGSd+JXcAP+CI2HRVp5LTaXin0eGsuPR2J1Mn6VAjQZToBVu59y260GaqG+QeMJJaKWjWOj4TtBIZFfkDN5X7L3QLUO5HhFJd3vQomUQjVv1N+lfEb3eqne337lSLESBGhFTWECV/gYLTa7RV0hubgqab6RpLSb49LmLcx0dv+V+STs9aSBlpmNB1EqMkZ0oHL/FN01pJGqAaFg4GSgSmJmFsf+Ftl/G8gl9RboyTUAibUAJJXqpGTVLkJT6cGE3L313wKSBk5QD0AUjhI52AvbWSWllBkcVv9/LrQRaR9WXTQU1fafMUlzhuqZ6r5/49ObvDl8hNwwNBafl9dRFwkFwG9Yrru325Xz4Ftfnb9acqkBVfN1chMUOW6+/khW4gQ9LIqsv7ppkggNyAA0+xzB/CYQtq1ph078bDmOpr+67hDwX1ZJy3HKTxtWA8DaxKWpyTtRLnaODlUlzyA2u0A6/8MVSRbWX3fX1ZN094PS/AebjG62xy4AcV79mSVSl1v3waOGWNr5yx2J0e0Z7pnn6Iac0NuA0iKzmLxSd/YlRWYBZqPj6bZO+dy3E57FeGfrkQp3F6Sxreyst96sSbrRDJ3zko7oLzGoxtxfdy67L0VDIlPBKrza6kuTTswUgugroFwI429kLk2eSjqqKoNA=
