name: Release
on:
  push:
    tags:
      - '*'

jobs:
  ci:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: IRC notification
        uses: Gottox/irc-message-action@v1
        with:
          channel: '#repla-development'
          nickname: repla-bot
          message: |-
            Deploy Started ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
      - run: carthage bootstrap
      - run: make archive
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: BubbleUp.framework.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: IRC notification
        uses: Gottox/irc-message-action@v1
        with:
          channel: '#repla-development'
          nickname: repla-bot
          message: |-
            Deploy finished ${{ github.actor }} pushed ${{ github.event.ref }} ${{ github.event.compare }}
